FROM golang:1.11

# install dep
RUN curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

# set working directory
RUN mkdir -p /go/src/github.com/christopher-wong/teslatrack
WORKDIR /go/src/github.com/christopher-wong/teslatrack

# add deps
ADD . .

# install packages, cached by docker
RUN dep ensure --vendor-only -v

EXPOSE 8000

WORKDIR /go/src/github.com/christopher-wong/teslatrack/cmd/teslatrackd
RUN go build .

# build binary and run bunary
CMD ["./teslatrackd"]

